### ISSUE TITLE
generator.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [Heleniuk/shop#6]
Немного не по феншую, как говорят, но тоже возможно.
Пока у этого сервиса нет зависимости, то все работает, но как только вы добавите зависимость, то код может перестать работать.
Это произойдет тогда, когда вы для сервиса добавите декоратор, а в конструкторе будет использоваться примитив. В вашем случае число.

**Comment by Heleniuk** [comment]
так имелось в виду? https://github.com/Heleniuk/shop/commit/9d6993ed3c33368708be397105d7d31a9baa4db8

**Comment by VZhyrytskiy** [comment]
Да
